spring.application.name=orbitcv

spring.datasource.url=jdbc:sqlite:data/orbitcv.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

server.port=8080

# Disable open session in view to avoid warnings
spring.jpa.open-in-view=false
