spring.application.name=orbitcv

spring.datasource.url=jdbc:sqlite:data/orbitcv.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080

spring.jpa.open-in-view=false

FRONTEND_ORIGIN=https://orbital-cv-frontend.onrender.com
FRONTEND_ORIGINS=https://orbital-cv-frontend.onrender.com,http://localhost:5173,http://localhost:63047
