spring.datasource.url=jdbc:sqlite:/tmp/orbitcv.db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

FRONTEND_ORIGIN=https://orbital-cv-frontend.onrender.com
FRONTEND_ORIGINS=https://orbital-cv-frontend.onrender.com
